In [1]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

plt.rcParams['axes.labelsize']=16
plt.rcParams['xtick.labelsize']=16
plt.rcParams['ytick.labelsize']=16
plt.rcParams['legend.fontsize']=14
plt.rcParams['lines.linewidth'] = 2
plt.rcParams['lines.markersize'] = 10
plt.rcParams['axes.labelsize'] = 20

In [2]:
import numpy as np

from DDAS import MakeReal
from AntennaSelection import generateSASdata 

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

data_prep_pipeline = Pipeline([
    ('toReal', MakeReal(RealPart = False, ImaginaryPart=False, magnitude = True, Phase = False)),
    ('stdScaler', StandardScaler()),
])

In [4]:
Nr = 2
Nt = 3

X,y = generateSASdata(1000,nt=Nt,nr=Nr)
X_test,y_test = generateSASdata(1000,nt = Nt,nr = Nr)

X_train = data_prep_pipeline.fit_transform(X)
X_test = data_prep_pipeline.transform(X_test)

In [5]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(sparse=False)
enc.fit(y.reshape(-1,1))
print(enc.n_values_)
y_train = enc.transform(y.reshape(-1,1))
y_test = enc.transform(y_test.reshape(-1,1))

[3]


In [6]:
print(y[0:5])
print(y_train.shape)
print(y_test.shape)
print(y_train)
print(y_test)

[0. 0. 0. 1. 2.]
(1000, 3)
(1000, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_predict, cross_val_score

In [8]:
rf_clf = RandomForestClassifier()
sgd_clf = SGDClassifier()
knearest_clf = KNeighborsClassifier(n_neighbors=201)

In [9]:
rf_scores = cross_val_score(rf_clf, X_train, y,cv=3 ,scoring="accuracy")
print(rf_scores)

[0.83233533 0.85928144 0.81626506]


In [10]:
sgd_scores = cross_val_score(sgd_clf, X_train, y,cv=3 ,scoring="accuracy")
print(sgd_scores)

[0.82035928 0.85329341 0.78915663]


/usr/lib64/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/usr/lib64/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/usr/lib64/python3.6/site-packages/sklearn/linea

In [11]:
knearest_scores = cross_val_score(knearest_clf, X_train, y, cv=3, scoring="accuracy")
print(knearest_scores)

[0.88622754 0.89221557 0.90361446]


In [12]:
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

In [13]:
gp_clf = GaussianProcessClassifier(1.0 * RBF(1.0), n_jobs=-1)
mlpc_clf = MLPClassifier(alpha=1)

In [14]:
#gp_scores = cross_val_score(gp_clf, X_train[0:1000,:], y[0:1000], cv=3, scoring="accuracy")
#print(gp_scores)

In [15]:
mlpc_scores = cross_val_score(mlpc_clf, X_train, y, cv=10,scoring="accuracy")
print(mlpc_scores)

/usr/lib64/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[0.93069307 0.97029703 0.95049505 0.97029703 0.94       0.94
 0.98       0.94949495 0.96969697 0.95918367]


In [16]:
from sklearn.naive_bayes import GaussianNB
nb_clf = GaussianNB()

In [17]:
nb_scores = cross_val_score(nb_clf, X_train, y, cv=10, scoring="accuracy")
print(nb_scores)

[0.91089109 0.95049505 0.97029703 0.97029703 0.93       0.93
 0.96       0.94949495 0.8989899  0.93877551]


In [18]:
from sklearn.svm import SVC
svc_clf = SVC()
svc_scores = cross_val_score(svc_clf,X_train[:10000,:], y[:10000], cv=3, scoring="accuracy")
print(svc_scores)

[0.90718563 0.94610778 0.92771084]
